title: Aliya Zhaxylykbayeva # your name (or website title) here
logo: "master/Logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Motivated and thorough professional, passionate about data storytelling and helping companies make data-driven decisions. 
  <br><br>

  <a href="https://www.linkedin.com/in/aliyazh/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
