title: Aliya Zhaxylykbayeva # your name (or website title) here
logo: "/Logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello and welcome to my portfolio! I'm a Technical Consultant at Capgemini during the day, and an avid data storyteller in the evening.
  
  <br><br>

  <a href="https://www.linkedin.com/in/aliyazh/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
